---
title: "Tools and recommendations for reproducible teaching"
author: "Mine Dogucu <br> University of California Irvine <br><br> Mine Çetinkaya-Rundel <br> Duke University"
date: "2025-03-12"
subtitle: "Talk at TALMO"
footer: "🔗 [mdogucu.github.io/talmo-25](https://mdogucu.github.io/talmo-25)"
format: 
  revealjs:
    slide-number: true
    incremental: true
    theme: style.scss
---

## 

[Dogucu, M., & Çetinkaya-Rundel, M. (2022). Tools and Recommendations for Reproducible Teaching. Journal of Statistics and Data Science Education, 30(3), 251–260. https://doi.org/10.1080/26939169.2022.2138645](https://www.tandfonline.com/doi/full/10.1080/26939169.2022.2138645)

. . .

with updated examples

## Teacher-Scholar's Toolkit

| Purpose  | Tool                |
|----------|---------------------|
| Research | R                   |
| Teaching | PowerPoint          |
| Learning | Graphing Calculator |


## Teacher-Scholar's Toolkit

| Purpose  | Tool                |
|----------|---------------------|
| Research | R                   |
| Teaching | R          |
| Learning | R |

## Teacher-Scholar's Toolkit

<style>
    .focus tr:nth-child(2) { background: gray; }
</style>

<div class="focus">

:::: {.columns}

::: {.column width="50%"}
| Purpose  | Tool                |
|----------|---------------------|
| Research | R                   |
| Teaching | PowerPoint          |
| Learning | Graphing Calculator |
:::

::: {.column width="50%"}
| Purpose  | Tool                |
|----------|---------------------|
| Research | R                   |
| Teaching | R          |
| Learning | R |
:::

::::

</div>

## Why?

- Course management
- Role modeling
- Sharing course materials with others

## Framework for Reproducible Teaching

All teaching materials should be

- computationally reproducible,

- well-documented, and

- open.

# Computational Reproducibility

## Literate programming

## Raw data

## File organization

## Version control

# Documentation

# Openness

##

[Dogucu, M. (In Press). Reproducibility in the Classroom. Annual Review of Statistics and Its Application.](https://www.annualreviews.org/content/journals/10.1146/annurev-statistics-112723-034436)

## QUESTIONS?

<br><br>

:::: {.columns}

::: {.column width="57%"}
{{< fa link >}} [minedogucu.com](https://www.minedogucu.com/)

{{< fa brands github >}} [mdogucu](https://github.com/mdogucu)

{{< fa brands mastodon >}} [mastodon.social/@MineDogucu](https://mastodon.social/@MineDogucu)

{{< fa brands bluesky >}} [minedogucu.com](https://bsky.app/profile/minedogucu.com)

{{< fa brands linkedin >}} [minedogucu](https://www.linkedin.com/in/minedogucu/)
:::

::: {.column width="43%"}
{{< fa link >}} [mine-cr.com](https://mine-cr.com)

{{< fa brands github >}} [mine-cetinkaya-rundel](https://github.com/mine-cetinkaya-rundel) 

{{< fa brands mastodon >}} [fosstodon.org/@minecr](https://fosstodon.org/@minecr)

{{< fa brands bluesky >}} [minecr.bsky.social](https://bsky.app/profile/minecr.bsky.social)

{{< fa brands linkedin >}} [minec](https://www.linkedin.com/in/minec/)
:::

::::


